blank_issues_enabled: false
contact_links:
  - name: Gareth Homepage
    url: https://garethpaul.com
    about: Ask questions and discuss the roadmap here.
  - name: GitHub Support - Feedback
    url: https://support.garethpaul.com
    about: Get support.